package za.co.gondwana.soft.entity.customer;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String customerCode;
     private int companyId;
     private String brick;
     private String country;
     private String customerDescription;
     private String customerName;
     private String latitude;
     private String longitude;
     private String region;
     private String reportingBlock;
     private String service;
     private String subRegion;

    public Customer() {
    }

	
    public Customer(String customerCode) {
        this.customerCode = customerCode;
    }
    public Customer(String customerCode, int companyId, String brick, String country, String customerDescription, String customerName, String latitude, String longitude, String region, String reportingBlock, String service, String subRegion) {
       this.customerCode = customerCode;
       this.companyId = companyId;
       this.brick = brick;
       this.country = country;
       this.customerDescription = customerDescription;
       this.customerName = customerName;
       this.latitude = latitude;
       this.longitude = longitude;
       this.region = region;
       this.reportingBlock = reportingBlock;
       this.service = service;
       this.subRegion = subRegion;
    }
   
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }
    public int getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(int companyId) {
        this.companyId = companyId;
    }
    public String getBrick() {
        return this.brick;
    }
    
    public void setBrick(String brick) {
        this.brick = brick;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getCustomerDescription() {
        return this.customerDescription;
    }
    
    public void setCustomerDescription(String customerDescription) {
        this.customerDescription = customerDescription;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getRegion() {
        return this.region;
    }
    
    public void setRegion(String region) {
        this.region = region;
    }
    public String getReportingBlock() {
        return this.reportingBlock;
    }
    
    public void setReportingBlock(String reportingBlock) {
        this.reportingBlock = reportingBlock;
    }
    public String getService() {
        return this.service;
    }
    
    public void setService(String service) {
        this.service = service;
    }
    public String getSubRegion() {
        return this.subRegion;
    }
    
    public void setSubRegion(String subRegion) {
        this.subRegion = subRegion;
    }




}


