package za.co.gondwana.soft.entity.product;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private String providerCode;
     private String productDescription;
     private String nappi9;
     private String nappi9Description;
     private String brand;
     private String businessUnit;
     private String productManager;
     private int countingUnits;

    public Product() {
    }

	
    public Product(String providerCode) {
        this.providerCode = providerCode;
    }
    public Product(String providerCode, String productDescription, String nappi9, String nappi9Description, String brand, String businessUnit, String productManager, int countingUnits) {
       this.providerCode = providerCode;
       this.productDescription = productDescription;
       this.nappi9 = nappi9;
       this.nappi9Description = nappi9Description;
       this.brand = brand;
       this.businessUnit = businessUnit;
       this.productManager = productManager;
       this.countingUnits = countingUnits;
    }
   
    public String getProviderCode() {
        return this.providerCode;
    }
    
    public void setProviderCode(String providerCode) {
        this.providerCode = providerCode;
    }
    public String getProductDescription() {
        return this.productDescription;
    }
    
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }
    public String getNappi9() {
        return this.nappi9;
    }
    
    public void setNappi9(String nappi9) {
        this.nappi9 = nappi9;
    }
    public String getNappi9Description() {
        return this.nappi9Description;
    }
    
    public void setNappi9Description(String nappi9Description) {
        this.nappi9Description = nappi9Description;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getBusinessUnit() {
        return this.businessUnit;
    }
    
    public void setBusinessUnit(String businessUnit) {
        this.businessUnit = businessUnit;
    }
    public String getProductManager() {
        return this.productManager;
    }
    
    public void setProductManager(String productManager) {
        this.productManager = productManager;
    }
    public int getCountingUnits() {
        return this.countingUnits;
    }
    
    public void setCountingUnits(int countingUnits) {
        this.countingUnits = countingUnits;
    }




}


