package za.co.gondwana.soft.entity.transaction;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * TransactionGroup generated by hbm2java
 */
public class TransactionGroup  implements java.io.Serializable {


     private String transactionGroup;

    public TransactionGroup() {
    }

    public TransactionGroup(String transactionGroup) {
       this.transactionGroup = transactionGroup;
    }
   
    public String getTransactionGroup() {
        return this.transactionGroup;
    }
    
    public void setTransactionGroup(String transactionGroup) {
        this.transactionGroup = transactionGroup;
    }




}


