package za.co.gondwana.soft.entity.transaction;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA


import java.math.BigDecimal;
import java.util.Date;

/**
 * TTTransaction generated by hbm2java
 */
public class TTTransaction  implements java.io.Serializable {


     private String productCode;
     private String customerCode;
     private String providerCode;
     private Date transactionDate;
     private String rep;
     private String rating;
     private BigDecimal units;
     private BigDecimal salesValue;

    public TTTransaction() {
    }

	
    public TTTransaction(String productCode) {
        this.productCode = productCode;
    }
    public TTTransaction(String productCode, String customerCode, String providerCode, Date transactionDate, String rep, String rating, BigDecimal units, BigDecimal salesValue) {
       this.productCode = productCode;
       this.customerCode = customerCode;
       this.providerCode = providerCode;
       this.transactionDate = transactionDate;
       this.rep = rep;
       this.rating = rating;
       this.units = units;
       this.salesValue = salesValue;
    }
   
    public String getProductCode() {
        return this.productCode;
    }
    
    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
    public String getCustomerCode() {
        return this.customerCode;
    }
    
    public void setCustomerCode(String customerCode) {
        this.customerCode = customerCode;
    }
    public String getProviderCode() {
        return this.providerCode;
    }
    
    public void setProviderCode(String providerCode) {
        this.providerCode = providerCode;
    }
    public Date getTransactionDate() {
        return this.transactionDate;
    }
    
    public void setTransactionDate(Date transactionDate) {
        this.transactionDate = transactionDate;
    }
    public String getRep() {
        return this.rep;
    }
    
    public void setRep(String rep) {
        this.rep = rep;
    }
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }
    public BigDecimal getUnits() {
        return this.units;
    }
    
    public void setUnits(BigDecimal units) {
        this.units = units;
    }
    public BigDecimal getSalesValue() {
        return this.salesValue;
    }
    
    public void setSalesValue(BigDecimal salesValue) {
        this.salesValue = salesValue;
    }




}


