package za.co.gondwana.soft.entity.manager;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * Manager generated by hbm2java
 */
public class Manager  implements java.io.Serializable {


     private int rep;
     private String repName;
     private String manager;
     private String managerName;

    public Manager() {
    }

	
    public Manager(int rep) {
        this.rep = rep;
    }
    public Manager(int rep, String repName, String manager, String managerName) {
       this.rep = rep;
       this.repName = repName;
       this.manager = manager;
       this.managerName = managerName;
    }
   
    public int getRep() {
        return this.rep;
    }
    
    public void setRep(int rep) {
        this.rep = rep;
    }
    public String getRepName() {
        return this.repName;
    }
    
    public void setRepName(String repName) {
        this.repName = repName;
    }
    public String getManager() {
        return this.manager;
    }
    
    public void setManager(String manager) {
        this.manager = manager;
    }
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }




}


