package za.co.arkitex.mobile.domain.growth;

public class GrowthConstants {

	// really :) constants wanna bes!
	/*
	 * used distinct, and removed nappi9description so that we have a simple result set.
	 */
	public static String getDefaultSQL(String date, String brick) {
		
//		calcMTDDates(date);
		
		String sql = "";
		sql += " SELECT DISTINCT ";
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
		sql += "	SUM (SalesValue) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";       
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
//		sql += " 	d.Comm_Month = 'Dec 2013' ";
		sql += " d.Comm_Month = '"+ date + "'";
		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += "	c.Brick  = '"+ brick + "'";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += "	b.Nappi9Description, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";  
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += " 	b.Nappi9Description, "; 
//		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
//		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'MTD Dec 2012', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM (SalesValue) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += " d.Comm_Month = '"+ date + "'";
		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += "	c.Brick  = '"+ brick + "'";	
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += "	b.Nappi9Description, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += "	b.Nappi9Description, "; 
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
//		sql += "	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'MTD Nov 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM (SalesValue) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
//		sql += "	d.Comm_Month = 'Nov 2013' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " d.Comm_Month = '"+ date + "'";
		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += "	c.Brick  = '"+ brick + "'";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += "	b.Nappi9Description, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";  
		sql += "	b.Brand, ";
		sql += "	c.Region, ";
//		sql += "	b.Nappi9Description, ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
//		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'YTD 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM (SalesValue) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";         
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
//		sql += "	d.Comm_Year = '2013' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " d.Comm_Year = '"+ date + "'";
		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += "	c.Brick  = '"+ brick + "'";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += "	b.Nappi9Description, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT DISTINCT "; 
		sql += "	b.Brand, ";
		sql += "	c.Region, ";
//		sql += "	b.Nappi9Description, ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
//		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
//		sql += "	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'YTD 2012' ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM (SalesValue) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
//		sql += "	d.Comm_Year = '2012' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " d.Comm_Year = '"+ date + "'";
		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += "	c.Brick  = '"+ brick + "'";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += "	b.Nappi9Description, ";
		sql += " 	c.Region ";
		return sql;
		
	}
	
	public static String getPreferentialSQL() {
		String sql = "";
		sql += " SELECT DISTINCT ";
		sql += "	b.Brand, ";
		sql += "	SUM (SalesValue) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";       
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += " 	d.Comm_Month = 'Dec 2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += " GROUP BY ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";  
		sql += "	b.Brand, ";
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM (SalesValue) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += "	d.Comm_Month = 'Dec 2012' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";
		sql += "	b.Brand, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM (SalesValue) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += "	d.Comm_Month = 'Nov 2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";  
		sql += "	b.Brand, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM (SalesValue) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";         
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += "	d.Comm_Year = '2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT "; 
		sql += "	b.Brand, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM (SalesValue) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += "	d.Comm_Year = '2012' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand ";
		return sql;
		
	}
	
	public static String getDefaultSQLWithNappi() {
		String sql = "";
		sql += " SELECT ";
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, ";
		sql += "	SUM (SalesValue) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";       
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += " 	d.Comm_Month = 'Dec 2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, "; 
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM (SalesValue) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += "	d.Comm_Month = 'Dec 2012' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
		sql += "	b.Nappi9Description, "; 
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM (SalesValue) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += "	d.Comm_Month = 'Nov 2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += "	b.Brand, ";
		sql += "	c.Region, ";
		sql += "	b.Nappi9Description, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM (SalesValue) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";         
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += "	d.Comm_Year = '2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand, ";
		sql += "	c.Region ";
		sql += " UNION ";
		sql += " SELECT "; 
		sql += "	b.Brand, ";
		sql += "	c.Region, ";
		sql += "	b.Nappi9Description, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM (SalesValue) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += "	d.Comm_Year = '2012' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand, ";
		sql += " 	c.Region ";
		return sql;
		
	}
	
	
	public static String getDefaultSQLWithOutRegion() {
		String sql = "";
		sql += " SELECT DISTINCT ";
		sql += "	b.Brand, ";
		sql += " 	b.Nappi9Description, ";
		sql += "	SUM (SalesValue) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";       
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += " 	d.Comm_Month = 'Dec 2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' " ;
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";  
		sql += "	b.Brand, ";
		sql += " 	b.Nappi9Description, "; 
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM (SalesValue) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += "	d.Comm_Month = 'Dec 2012' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";
		sql += "	b.Brand, ";
		sql += "	b.Nappi9Description, "; 
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM (SalesValue) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += "	d.Comm_Month = 'Nov 2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT ";  
		sql += "	b.Brand, ";
		sql += "	b.Nappi9Description, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM (SalesValue) AS 'YTD 2013', ";
		sql += "	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";         
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += "	d.Comm_Year = '2013' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand ";
		sql += " UNION ";
		sql += " SELECT DISTINCT "; 
		sql += "	b.Brand, ";
		sql += "	b.Nappi9Description, ";
		sql += "	SUM(0) AS 'MTD Dec 2013', ";
		sql += "	SUM(0) AS 'MTD Dec 2012', ";
		sql += "	SUM(0) AS 'MTD Nov 2013', ";
		sql += "	SUM(0) AS 'YTD 2013', ";
		sql += "	SUM (SalesValue) AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += "	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += "	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += "	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += "	vw_CUBE_Times d ";
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";       
		sql += "	d.Comm_Year = '2012' ";
		sql += " AND ";
		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Nappi9Description, ";
		sql += "	b.Brand ";
		return sql;
		
	}
	
	// lets pass a rep id in here.
	public static String getRepSalesGrowthSQL(String repId) {
		
		String sql = "";
		sql += " SELECT ";
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	SUM (SalesValue) AS 'MTD Dec 2013', ";
		sql += " 	SUM(0) AS 'MTD Dec 2012', ";
		sql += " 	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM(0) AS 'YTD 2013', ";
		sql += " 	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c "; 
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";
		sql += " 	a.Rep = '" + repId+ "' ";
		sql += " AND ";    
		sql += " 	d.Comm_Month = 'Dec 2013' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += " 	b.Nappi9Description, "; 
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM (SalesValue) AS 'MTD Dec 2012', ";
		sql += " 	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM(0) AS 'YTD 2013', ";
		sql += " 	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";  
		sql += " 	a.Rep = '" + repId +"' ";
		sql += " AND ";    
		sql += " 	d.Comm_Month = 'Dec 2012' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM(0) AS 'MTD Dec 2012', ";
		sql += " 	SUM (SalesValue) AS 'MTD Nov 2013', ";
		sql += " 	SUM(0) AS 'YTD 2013', ";
		sql += " 	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";    
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";
		sql += " 	a.Rep = '" + repId +"' ";
		sql += " AND ";   
		sql += " 	d.Comm_Month = 'Nov 2013' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM(0) AS 'MTD Dec 2012', ";
		sql += " 	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM (SalesValue) AS 'YTD 2013', ";
		sql += " 	SUM(0) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " 	INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";
		sql += " 	a.Rep = '0008' ";
		sql += " AND ";    
		sql += " 	d.Comm_Year = '2013' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += "	b.Brand, ";
		sql += " 	c.Region, ";
//		sql += " 	b.Nappi9Description, "; 
		sql += " 	SUM(0) AS 'MTD Dec 2013', ";
		sql += " 	SUM(0) AS 'MTD Dec 2012', ";
		sql += " 	SUM(0) AS 'MTD Nov 2013', ";
		sql += " 	SUM(0) AS 'YTD 2013', ";
		sql += " 	SUM (SalesValue) AS 'YTD 2012' ";
		sql += " FROM ";           
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE "; 
		sql += " 	a.Rep = '" + repId +"' ";
		sql += " AND ";     
		sql += " 	d.Comm_Year = '2012' ";
//		sql += " AND ";
//		sql += "	c.Brick = 'LEA GLEN +S - 4924' ";
		sql += " GROUP BY ";
		sql += "	b.Brand, ";
//		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		return sql;
	}
	
	
	public static String getProductSalesGrowthSQL(String product) {
		
		String sql = "";
		sql += " SELECT ";
		sql += " 	b.Brand, ";  
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'MTD Dec 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";  
		sql += " 	d.Comm_Month = 'Dec 2013' ";
		sql += " AND ";
		sql += " 	b.Brand = '" +product +"' ";
		sql += " GROUP BY ";
		sql += " 	b.Brand, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";
		sql += " 	b.Brand, ";
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'MTD Dec 2012', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += " FROM ";          
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";
		sql += " 	d.Comm_Month = 'Dec 2012' ";
		sql += " AND ";
		sql += " 	b.Brand = '" +product +"' ";
		sql += " GROUP BY ";
		sql += " 	b.Brand, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += " 	b.Brand, ";
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, "; 
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'MTD Nov 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += " FROM ";
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";
		sql += " 	d.Comm_Month = 'Nov 2013' ";
		sql += " AND ";
		sql += " 	b.Brand = '"+ product +"' ";
		sql += " GROUP BY ";
		sql += " 	b.Brand, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT "; 
		sql += " 	b.Brand, ";
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'YTD 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'YTD 2012' ";
		sql += " FROM ";
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d "; 
		sql += " ON ";
		sql += "	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";
		sql += " 	d.Comm_Year = '2013' ";
		sql += " AND ";
		sql += " 	b.Brand = '"+product+"' ";
		sql += " GROUP BY ";
		sql += " 	b.Brand, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region ";
		sql += " UNION ";
		sql += " SELECT ";  
		sql += " 	b.Brand, ";
		sql += " 	c.Region, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2013', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Dec 2012', ";
		sql += " 	FORMAT(0, 'C', 'en-za') AS 'MTD Nov 2013', ";
		sql += "	FORMAT(0, 'C', 'en-za') AS 'YTD 2013', ";
		sql += " 	FORMAT(SUM (SalesValue), 'C', 'en-za') AS 'YTD 2012' ";
		sql += " FROM ";
		sql += " 	vw_CUBE_FACT_TT_Transactions a ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Products b ";
		sql += " ON ";
		sql += " 	a.ProductCode = b.ProductCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Customers c ";
		sql += " ON ";
		sql += " 	a.CustomerCode = c.CustomerCode ";
		sql += " INNER JOIN ";
		sql += " 	vw_CUBE_Times d ";
		sql += " ON ";
		sql += " 	CAST (a.TransactionDate AS DATE)   = d.Date ";
		sql += " WHERE ";      
		sql += " 	d.Comm_Year = '2012' ";
		sql += " AND ";
		sql += " 	b.Brand = '"+product+"' ";
		sql += " GROUP BY ";
		sql += " 	b.Brand, ";
		sql += " 	b.Nappi9Description, ";
		sql += " 	c.Region";
		
		return sql;
	}
	
	
	public SalesGrowthColumn calcMTDDates(String date) {
		
		
		
		return null;
	}
}
