package za.co.gondwana.soft.entity.provider;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * Provider generated by hbm2java
 */
public class Provider  implements java.io.Serializable {


     private String providerCode;
     private String provider;
     private String providerBranch;
     private String providerBranchName;
     private String providerGroup;
     private String medPagesChannel;
     private String providerMainGroup;

    public Provider() {
    }

	
    public Provider(String providerCode) {
        this.providerCode = providerCode;
    }
    public Provider(String providerCode, String provider, String providerBranch, String providerBranchName, String providerGroup, String medPagesChannel, String providerMainGroup) {
       this.providerCode = providerCode;
       this.provider = provider;
       this.providerBranch = providerBranch;
       this.providerBranchName = providerBranchName;
       this.providerGroup = providerGroup;
       this.medPagesChannel = medPagesChannel;
       this.providerMainGroup = providerMainGroup;
    }
   
    public String getProviderCode() {
        return this.providerCode;
    }
    
    public void setProviderCode(String providerCode) {
        this.providerCode = providerCode;
    }
    public String getProvider() {
        return this.provider;
    }
    
    public void setProvider(String provider) {
        this.provider = provider;
    }
    public String getProviderBranch() {
        return this.providerBranch;
    }
    
    public void setProviderBranch(String providerBranch) {
        this.providerBranch = providerBranch;
    }
    public String getProviderBranchName() {
        return this.providerBranchName;
    }
    
    public void setProviderBranchName(String providerBranchName) {
        this.providerBranchName = providerBranchName;
    }
    public String getProviderGroup() {
        return this.providerGroup;
    }
    
    public void setProviderGroup(String providerGroup) {
        this.providerGroup = providerGroup;
    }
    public String getMedPagesChannel() {
        return this.medPagesChannel;
    }
    
    public void setMedPagesChannel(String medPagesChannel) {
        this.medPagesChannel = medPagesChannel;
    }
    public String getProviderMainGroup() {
        return this.providerMainGroup;
    }
    
    public void setProviderMainGroup(String providerMainGroup) {
        this.providerMainGroup = providerMainGroup;
    }




}


