package za.co.gondwana.soft.entity.rating;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private String rating;

    public Rating() {
    }

    public Rating(String rating) {
       this.rating = rating;
    }
   
    public String getRating() {
        return this.rating;
    }
    
    public void setRating(String rating) {
        this.rating = rating;
    }




}


