<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xsObject>
    <appSmsCode></appSmsCode>
    <sharePointRoot>
        <name>SharePoint Servers</name>
    </sharePointRoot>
    <wsdlroot>
        <wsdltree>
            <name>Web Services</name>
            <wsdlservice>
                <authenticationMode>basic</authenticationMode>
                <loaded>true</loaded>
                <name>SalesRepresentativeService</name>
                <ntlmDomain></ntlmDomain>
                <ntlmHost></ntlmHost>
                <password></password>
                <preBuilt>false</preBuilt>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>getDateFilter</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://interfaces.ws.gondwana.mobile.arkitex.co.za/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;int:getDateFilter&gt;
         &lt;date&gt;?&lt;/date&gt;
      &lt;/int:getDateFilter&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;</intemplate>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>getDateFilter</operationname>
                    <outtemplate></outtemplate>
                    <outTemplateHeader></outTemplateHeader>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://209.203.36.130:8080/com/arkitex/mobile</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
                </soapservice>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>getBrandsByDate</id>
                    <ignoreProxy>false</ignoreProxy>
                    <inparam>
                        <category></category>
                        <datatype>string</datatype>
                        <defaultvalue></defaultvalue>
                        <description></description>
                        <encode>true</encode>
                        <format>None</format>
                        <formatvalue></formatvalue>
                        <id>repId</id>
                        <invalue></invalue>
                        <name></name>
                        <order></order>
                        <passNull>false</passNull>
                        <recordid></recordid>
                        <smsname></smsname>
                        <source></source>
                        <srcformatvalue></srcformatvalue>
                        <target></target>
                        <targetdatatype></targetdatatype>
                        <testvalue>0008</testvalue>
                        <value></value>
                    </inparam>
                    <inparam>
                        <category></category>
                        <datatype>string</datatype>
                        <defaultvalue></defaultvalue>
                        <description></description>
                        <encode>true</encode>
                        <format>None</format>
                        <formatvalue></formatvalue>
                        <id>date</id>
                        <invalue></invalue>
                        <name></name>
                        <order></order>
                        <passNull>false</passNull>
                        <recordid></recordid>
                        <smsname></smsname>
                        <source></source>
                        <srcformatvalue></srcformatvalue>
                        <target></target>
                        <targetdatatype></targetdatatype>
                        <testvalue>2013</testvalue>
                        <value></value>
                    </inparam>
                    <intemplate>&lt;soapenv:Envelope xmlns:int="http://interfaces.ws.gondwana.mobile.arkitex.co.za/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;int:getBrandsByDate&gt;
         &lt;repId&gt;0008&lt;/repId&gt;
         &lt;date&gt;2013&lt;/date&gt;
      &lt;/int:getBrandsByDate&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;
</intemplate>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>getBrandsByDate</operationname>
                    <outtemplate>&lt;S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"&gt;
   &lt;S:Body&gt;
      &lt;ns2:getBrandsByDateResponse xmlns:ns2="http://interfaces.ws.gondwana.mobile.arkitex.co.za/"&gt;
         &lt;return&gt;
            &lt;item&gt;Product 11&lt;/item&gt;
            &lt;item&gt;Product 12&lt;/item&gt;
            &lt;item&gt;Product 13&lt;/item&gt;
            &lt;item&gt;Product 14&lt;/item&gt;
            &lt;item&gt;Product 2&lt;/item&gt;
            &lt;item&gt;Product 22&lt;/item&gt;
            &lt;item&gt;Product 23&lt;/item&gt;
            &lt;item&gt;Product 28&lt;/item&gt;
            &lt;item&gt;Product 6&lt;/item&gt;
            &lt;item&gt;Product 7&lt;/item&gt;
         &lt;/return&gt;
      &lt;/ns2:getBrandsByDateResponse&gt;
   &lt;/S:Body&gt;
&lt;/S:Envelope&gt;
</outtemplate>
                    <outTemplateHeader>Transfer-encoding: chunked
Content-type: text/xml;charset="utf-8"
</outTemplateHeader>
                    <outparam>
                        <category></category>
                        <datatype>string</datatype>
                        <defaultvalue></defaultvalue>
                        <description></description>
                        <encode>true</encode>
                        <format>None</format>
                        <formatvalue></formatvalue>
                        <id>period</id>
                        <invalue></invalue>
                        <name></name>
                        <order></order>
                        <passNull>false</passNull>
                        <recordid></recordid>
                        <smsname></smsname>
                        <source>//return</source>
                        <srcformatvalue></srcformatvalue>
                        <target></target>
                        <targetdatatype></targetdatatype>
                        <testvalue></testvalue>
                        <value></value>
                    </outparam>
                    <outparam>
                        <category></category>
                        <datatype>string</datatype>
                        <defaultvalue></defaultvalue>
                        <description></description>
                        <encode>true</encode>
                        <format>None</format>
                        <formatvalue></formatvalue>
                        <id>item</id>
                        <invalue></invalue>
                        <name></name>
                        <order></order>
                        <passNull>false</passNull>
                        <recordid></recordid>
                        <smsname></smsname>
                        <source>item</source>
                        <srcformatvalue></srcformatvalue>
                        <target>response</target>
                        <targetdatatype></targetdatatype>
                        <testvalue></testvalue>
                        <value>period</value>
                    </outparam>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://209.203.36.130:8080/com/arkitex/mobile</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
                </soapservice>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>getSalesTrendDataByProduct</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://interfaces.ws.gondwana.mobile.arkitex.co.za/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;int:getSalesTrendDataByProduct&gt;
         &lt;repId&gt;?&lt;/repId&gt;
         &lt;product&gt;?&lt;/product&gt;
         &lt;date&gt;?&lt;/date&gt;
      &lt;/int:getSalesTrendDataByProduct&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;</intemplate>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>getSalesTrendDataByProduct</operationname>
                    <outtemplate></outtemplate>
                    <outTemplateHeader></outTemplateHeader>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://209.203.36.130:8080/com/arkitex/mobile</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
                </soapservice>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>getSalesTrendData</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://interfaces.ws.gondwana.mobile.arkitex.co.za/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;int:getSalesTrendData&gt;
         &lt;repId&gt;?&lt;/repId&gt;
         &lt;date&gt;?&lt;/date&gt;
      &lt;/int:getSalesTrendData&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;</intemplate>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>getSalesTrendData</operationname>
                    <outtemplate></outtemplate>
                    <outTemplateHeader></outTemplateHeader>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://209.203.36.130:8080/com/arkitex/mobile</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
                </soapservice>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>getMyTop25Customers</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://interfaces.ws.gondwana.mobile.arkitex.co.za/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;int:getMyTop25Customers&gt;
         &lt;repId&gt;?&lt;/repId&gt;
         &lt;date&gt;?&lt;/date&gt;
      &lt;/int:getMyTop25Customers&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;</intemplate>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>getMyTop25Customers</operationname>
                    <outtemplate></outtemplate>
                    <outTemplateHeader></outTemplateHeader>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://209.203.36.130:8080/com/arkitex/mobile</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
                </soapservice>
                <soapservice>
                    <authenticationMode>basic</authenticationMode>
                    <cacheduration></cacheduration>
                    <cacheable>false</cacheable>
                    <dataprovider></dataprovider>
                    <dcResponse/>
                    <encryptPwd>true</encryptPwd>
                    <escapeXML>false</escapeXML>
                    <id>getMySalesVisualized</id>
                    <ignoreProxy>false</ignoreProxy>
                    <intemplate>&lt;soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:int="http://interfaces.ws.gondwana.mobile.arkitex.co.za/"&gt;
   &lt;soapenv:Header/&gt;
   &lt;soapenv:Body&gt;
      &lt;int:getMySalesVisualized&gt;
         &lt;repId&gt;?&lt;/repId&gt;
         &lt;date&gt;?&lt;/date&gt;
      &lt;/int:getMySalesVisualized&gt;
   &lt;/soapenv:Body&gt;
&lt;/soapenv:Envelope&gt;</intemplate>
                    <ntlmDomain></ntlmDomain>
                    <ntlmHost></ntlmHost>
                    <operationname>getMySalesVisualized</operationname>
                    <outtemplate></outtemplate>
                    <outTemplateHeader></outTemplateHeader>
                    <password></password>
                    <postclassname></postclassname>
                    <preclassname></preclassname>
                    <proxyname></proxyname>
                    <proxyport></proxyport>
                    <proxypwd></proxypwd>
                    <proxyuserid></proxyuserid>
                    <responseencoding>UTF-8</responseencoding>
                    <sharePoint>false</sharePoint>
                    <smscode></smscode>
                    <smsenabled>false</smsenabled>
                    <soapaction></soapaction>
                    <timeout></timeout>
                    <url>http://209.203.36.130:8080/com/arkitex/mobile</url>
                    <urlprovider></urlprovider>
                    <userid></userid>
                    <version>1.1</version>
                    <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
                </soapservice>
                <sharePoint>false</sharePoint>
                <userName></userName>
                <wsdlurl>http://209.203.36.130:8080/com/arkitex/mobile?wsdl</wsdlurl>
            </wsdlservice>
        </wsdltree>
    </wsdlroot>
</xsObject>
