package za.co.gondwana.soft.entity.market;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA



/**
 * Market generated by hbm2java
 */
public class Market  implements java.io.Serializable {


     private String market;

    public Market() {
    }

    public Market(String market) {
       this.market = market;
    }
   
    public String getMarket() {
        return this.market;
    }
    
    public void setMarket(String market) {
        this.market = market;
    }




}


