package za.co.gondwana.soft.entity.time;
// Generated Sep 6, 2014 2:19:21 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * Time generated by hbm2java
 */
public class Time  implements java.io.Serializable {


     private Date timesDate;
     private String dateName;
     private String calendarMonth;
     private String calendarQuarter;
     private int calendarYear;
     private int calendarMonthOfYear;
     private String calendarMonthOfYearName;
     private String calendarQuarterOfYear;
     private String commMonth;
     private String commQuarter;
     private int commYear;
     private int commMonthOfYear;
     private String commMonthOfYearName;
     private String commQuarterOfYear;
     private String fiscalMonth;
     private String fiscalQuarter;
     private int fiscalYear;
     private int fiscalMonthOfYear;
     private String managerName;
     private String fiscalMonthOfYearName;
     private String fiscalQuarterOfYear;
     private boolean tradingDay;

    public Time() {
    }

	
    public Time(Date timesDate) {
        this.timesDate = timesDate;
    }
    public Time(Date timesDate, String dateName, String calendarMonth, String calendarQuarter, int calendarYear, int calendarMonthOfYear, String calendarMonthOfYearName, String calendarQuarterOfYear, String commMonth, String commQuarter, int commYear, int commMonthOfYear, String commMonthOfYearName, String commQuarterOfYear, String fiscalMonth, String fiscalQuarter, int fiscalYear, int fiscalMonthOfYear, String managerName, String fiscalMonthOfYearName, String fiscalQuarterOfYear, boolean tradingDay) {
       this.timesDate = timesDate;
       this.dateName = dateName;
       this.calendarMonth = calendarMonth;
       this.calendarQuarter = calendarQuarter;
       this.calendarYear = calendarYear;
       this.calendarMonthOfYear = calendarMonthOfYear;
       this.calendarMonthOfYearName = calendarMonthOfYearName;
       this.calendarQuarterOfYear = calendarQuarterOfYear;
       this.commMonth = commMonth;
       this.commQuarter = commQuarter;
       this.commYear = commYear;
       this.commMonthOfYear = commMonthOfYear;
       this.commMonthOfYearName = commMonthOfYearName;
       this.commQuarterOfYear = commQuarterOfYear;
       this.fiscalMonth = fiscalMonth;
       this.fiscalQuarter = fiscalQuarter;
       this.fiscalYear = fiscalYear;
       this.fiscalMonthOfYear = fiscalMonthOfYear;
       this.managerName = managerName;
       this.fiscalMonthOfYearName = fiscalMonthOfYearName;
       this.fiscalQuarterOfYear = fiscalQuarterOfYear;
       this.tradingDay = tradingDay;
    }
   
    public Date getTimesDate() {
        return this.timesDate;
    }
    
    public void setTimesDate(Date timesDate) {
        this.timesDate = timesDate;
    }
    public String getDateName() {
        return this.dateName;
    }
    
    public void setDateName(String dateName) {
        this.dateName = dateName;
    }
    public String getCalendarMonth() {
        return this.calendarMonth;
    }
    
    public void setCalendarMonth(String calendarMonth) {
        this.calendarMonth = calendarMonth;
    }
    public String getCalendarQuarter() {
        return this.calendarQuarter;
    }
    
    public void setCalendarQuarter(String calendarQuarter) {
        this.calendarQuarter = calendarQuarter;
    }
    public int getCalendarYear() {
        return this.calendarYear;
    }
    
    public void setCalendarYear(int calendarYear) {
        this.calendarYear = calendarYear;
    }
    public int getCalendarMonthOfYear() {
        return this.calendarMonthOfYear;
    }
    
    public void setCalendarMonthOfYear(int calendarMonthOfYear) {
        this.calendarMonthOfYear = calendarMonthOfYear;
    }
    public String getCalendarMonthOfYearName() {
        return this.calendarMonthOfYearName;
    }
    
    public void setCalendarMonthOfYearName(String calendarMonthOfYearName) {
        this.calendarMonthOfYearName = calendarMonthOfYearName;
    }
    public String getCalendarQuarterOfYear() {
        return this.calendarQuarterOfYear;
    }
    
    public void setCalendarQuarterOfYear(String calendarQuarterOfYear) {
        this.calendarQuarterOfYear = calendarQuarterOfYear;
    }
    public String getCommMonth() {
        return this.commMonth;
    }
    
    public void setCommMonth(String commMonth) {
        this.commMonth = commMonth;
    }
    public String getCommQuarter() {
        return this.commQuarter;
    }
    
    public void setCommQuarter(String commQuarter) {
        this.commQuarter = commQuarter;
    }
    public int getCommYear() {
        return this.commYear;
    }
    
    public void setCommYear(int commYear) {
        this.commYear = commYear;
    }
    public int getCommMonthOfYear() {
        return this.commMonthOfYear;
    }
    
    public void setCommMonthOfYear(int commMonthOfYear) {
        this.commMonthOfYear = commMonthOfYear;
    }
    public String getCommMonthOfYearName() {
        return this.commMonthOfYearName;
    }
    
    public void setCommMonthOfYearName(String commMonthOfYearName) {
        this.commMonthOfYearName = commMonthOfYearName;
    }
    public String getCommQuarterOfYear() {
        return this.commQuarterOfYear;
    }
    
    public void setCommQuarterOfYear(String commQuarterOfYear) {
        this.commQuarterOfYear = commQuarterOfYear;
    }
    public String getFiscalMonth() {
        return this.fiscalMonth;
    }
    
    public void setFiscalMonth(String fiscalMonth) {
        this.fiscalMonth = fiscalMonth;
    }
    public String getFiscalQuarter() {
        return this.fiscalQuarter;
    }
    
    public void setFiscalQuarter(String fiscalQuarter) {
        this.fiscalQuarter = fiscalQuarter;
    }
    public int getFiscalYear() {
        return this.fiscalYear;
    }
    
    public void setFiscalYear(int fiscalYear) {
        this.fiscalYear = fiscalYear;
    }
    public int getFiscalMonthOfYear() {
        return this.fiscalMonthOfYear;
    }
    
    public void setFiscalMonthOfYear(int fiscalMonthOfYear) {
        this.fiscalMonthOfYear = fiscalMonthOfYear;
    }
    public String getManagerName() {
        return this.managerName;
    }
    
    public void setManagerName(String managerName) {
        this.managerName = managerName;
    }
    public String getFiscalMonthOfYearName() {
        return this.fiscalMonthOfYearName;
    }
    
    public void setFiscalMonthOfYearName(String fiscalMonthOfYearName) {
        this.fiscalMonthOfYearName = fiscalMonthOfYearName;
    }
    public String getFiscalQuarterOfYear() {
        return this.fiscalQuarterOfYear;
    }
    
    public void setFiscalQuarterOfYear(String fiscalQuarterOfYear) {
        this.fiscalQuarterOfYear = fiscalQuarterOfYear;
    }
    public boolean isTradingDay() {
        return this.tradingDay;
    }
    
    public void setTradingDay(boolean tradingDay) {
        this.tradingDay = tradingDay;
    }




}


